version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      BOT_TOKEN: $BOT_TOKEN 
      APP_NAME: $APP_NAME
      BIN_CHANNEL: $BIN_CHANNEL
      DATABASE_URL: $DATABASE_URL
      OWNER_ID: $OWNER_ID
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      OWNER_USERNAME: $OWNER_USERNAME
      SESSION_NAME: $SESSION_NAME
      HAS_SSL: $HAS_SSL
      NO_PORT: $NO_PORT
      PORT: $PORT
